### ISSUE TITLE
"Uncaught Exception: Invalid Note Code VF4"

### ISSUE THREAD

**Issue by Packetdancer** [buff0000n/shawzinscore#3]
So, I've got a complicated and not-entirely-fully-baked shawzin tune I'm working on -- an attempt to arrange Christopher Tin's "Baba Yetu" for shawzin -- and I tried pasting the opening portion into this viewer.

It's worth noting the code was generated from Vinchenzo's [Shawzin Composer](https://vinchenzo.gitlab.io/warframe-shawzin-composer/) tool, but it pastes fine into the game and your own Shawzin Tab Generator. Here, however, it generates an uncaught 'invalid note' exception.

I grant this is a _terrible_ test case, given that it does some very unhealthy/unholy things with trying to simulate chords (poorly), but still...

```
5CAARAIRAQMAYMAcKAkKAsKAwSA4SBARBIRBQKBYKBcMBkRBsRBwUB4hCARCIRCQMCYMCcKCkKCsKCwUC4UDAKDIKDQRDYSDcRDkRDsRDwMD4KD8CEACEHREIKEJCEPREQKEREEYMEZBEaEEcMEdBEeCEkKElCEsKEtCEwKExEE4KE5SE6EFAKFBSFCCFIKFJRFKCFQKFRRFSCFYKFZCFcKFdEFkMFlKFsRFtKFwRFxVF4KGARGBhGCKGIRGJKGQRGRMGYMGcEGkKGlEGsKGtEGwKGxEG4KG5UG6EHAKHBUHCEHIKHJEHQKHREHYKHZRHaCHcSHdCHkRHlCHsRHtCHwRHxCH4MH5
```

**Comment by buff0000n** [comment]
I'm not in front of the game right now, but what does two strings in the same note actually do in-game?

**Comment by buff0000n** [comment]
Interesting.  I added a check for multi-string notes to Shawzinscore assuming it wasn't allowed, but it turns out you can do it, with some caveats.  Supporting it in Shawzinscore was a lot more complicated than in Shawzintab, but it should work now.

**Comment by Packetdancer** [comment]
Yay! Thank you. I am also admittedly mildly amused that it's the rare place I could do a chord _properly_ in that which caused problems, rather than my horrific attempts to emulate them with very quickly strummed notes.

(But yes, there are many, _many_ caveats to it.)
